version: '3.3'
services:
  db:
    image: postgres:15
    container_name: db
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  queue:
    image: rabbitmq:3-management
    container_name: queue
    env_file:
      - .env
    ports:
      - 15672:15672
    hostname: queue

  redis:
    image: redis:7
    container_name: redis
    env_file:
      - .env
  
  backend:
    image: '${DOCKER_USER}/${DOCKER_IMAGE_BACKEND}:latest'
    container_name: backend
    depends_on:
      - db
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command: 'uvicorn app.main:app --host 0.0.0.0 --port 8080'

  celeryworker:
    image: '${DOCKER_USER}/${DOCKER_IMAGE_BACKEND}:latest'
    container_name: celery-worker
    depends_on:
      - db
      - queue
      - redis
    env_file:
      - .env
    command: 'celery -A app.worker worker -l info'

  flower:
    image: '${DOCKER_USER}/${DOCKER_IMAGE_BACKEND}:latest'
    container_name: flower
    depends_on:
      - celeryworker
    env_file:
      - .env
    command: 'celery -A app.worker flower --broker=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@queue:5672//'
    ports:
      - 5555:5555
  
volumes:
  app-db-data:
