"""empty message

Revision ID: 0242b65484e0
Revises: 8613b4042fff
Create Date: 2023-07-27 11:15:28.585321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0242b65484e0'
down_revision = '8613b4042fff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticker', 'price')
    # ### end Alembic commands ###
