"""empty message

Revision ID: 26304747a3e5
Revises: fe0ed9874502
Create Date: 2023-09-09 09:05:09.453052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26304747a3e5'
down_revision = 'fe0ed9874502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'refresh_token')
    # ### end Alembic commands ###
