"""empty message

Revision ID: 3a9895d5384e
Revises: 26304747a3e5
Create Date: 2023-09-10 08:18:52.564070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3a9895d5384e"
down_revision = "26304747a3e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "refresh_token")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("refresh_token", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
