"""empty message

Revision ID: 537ae9985509
Revises: 4b778bb52743
Create Date: 2023-08-03 09:04:02.339492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "537ae9985509"
down_revision = "4b778bb52743"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_portfolio_order_id", table_name="portfolio_order")
    op.add_column("portfolio", sa.Column("is_running", sa.Boolean(), nullable=False))
    op.add_column("portfolio", sa.Column("amount", sa.Integer(), nullable=False))
    op.add_column(
        "portfolio_transaction",
        sa.Column("portfolio_ticker_id", sa.Integer(), nullable=True),
    )
    op.drop_constraint(
        "portfolio_transaction_ticker_id_fkey",
        "portfolio_transaction",
        type_="foreignkey",
    )
    op.drop_constraint(
        "portfolio_transaction_portfolio_order_id_fkey",
        "portfolio_transaction",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "portfolio_transaction",
        "portfolio_ticker",
        ["portfolio_ticker_id"],
        ["id"],
    )
    op.drop_column("portfolio_transaction", "ticker_id")
    op.drop_column("portfolio_transaction", "portfolio_order_id")
    op.drop_table("portfolio_order")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "portfolio_transaction",
        sa.Column(
            "portfolio_order_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "portfolio_transaction",
        sa.Column("ticker_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "portfolio_transaction", type_="foreignkey")
    op.create_foreign_key(
        "portfolio_transaction_portfolio_order_id_fkey",
        "portfolio_transaction",
        "portfolio_order",
        ["portfolio_order_id"],
        ["id"],
    )
    op.create_foreign_key(
        "portfolio_transaction_ticker_id_fkey",
        "portfolio_transaction",
        "ticker",
        ["ticker_id"],
        ["id"],
    )
    op.drop_column("portfolio_transaction", "portfolio_ticker_id")
    op.drop_column("portfolio", "amount")
    op.drop_column("portfolio", "is_running")
    op.create_table(
        "portfolio_order",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("portfolio_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("is_running", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("amount", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"], ["portfolio.id"], name="portfolio_order_portfolio_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="portfolio_order_pkey"),
    )
    op.create_index("ix_portfolio_order_id", "portfolio_order", ["id"], unique=False)
    # ### end Alembic commands ###
