"""empty message

Revision ID: 55a3f107b874
Revises: 0242b65484e0
Create Date: 2023-07-31 10:00:47.480245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a3f107b874'
down_revision = '0242b65484e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
