"""empty message

Revision ID: 5e511bee92e3
Revises: 02e48b9eef78
Create Date: 2023-07-20 15:03:35.717675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e511bee92e3'
down_revision = '02e48b9eef78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'exchange_key', ['user_id', 'exchange_id'])
    op.add_column('portfolio_transaction', sa.Column('order_type', sa.String(length=10), nullable=True))
    op.drop_column('portfolio_transaction', 'order_type_id')
    op.add_column('simple_transaction', sa.Column('order_type', sa.String(length=10), nullable=True))
    op.alter_column('simple_transaction', 'uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('simple_transaction', 'is_fiiled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('simple_transaction', 'order_type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simple_transaction', sa.Column('order_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('simple_transaction', 'is_fiiled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('simple_transaction', 'uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('simple_transaction', 'order_type')
    op.add_column('portfolio_transaction', sa.Column('order_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('portfolio_transaction', 'order_type')
    op.drop_constraint(None, 'exchange_key', type_='unique')
    # ### end Alembic commands ###
