"""empty message

Revision ID: 64ceb22eb435
Revises: dba38207abb4
Create Date: 2023-08-02 10:20:24.911225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "64ceb22eb435"
down_revision = "dba38207abb4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_strategy_id", table_name="strategy")
    op.drop_constraint(
        "portfolio_order_strategy_id_fkey", "portfolio_order", type_="foreignkey"
    )
    op.drop_column("portfolio_order", "strategy_id")
    op.drop_table("strategy")
    # op.execute("DROP TABLE IF EXISTS strategy CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "portfolio_order",
        sa.Column("strategy_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "portfolio_order_strategy_id_fkey",
        "portfolio_order",
        "strategy",
        ["strategy_id"],
        ["id"],
    )
    op.create_table(
        "strategy",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "strategy_nm", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "strategy_knm", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column("strategy_desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="strategy_pkey"),
        sa.UniqueConstraint("strategy_knm", name="strategy_strategy_knm_key"),
        sa.UniqueConstraint("strategy_nm", name="strategy_strategy_nm_key"),
    )
    op.create_index("ix_strategy_id", "strategy", ["id"], unique=False)
    # ### end Alembic commands ###
