"""empty message

Revision ID: 65a8684cf235
Revises: 537ae9985509
Create Date: 2023-08-10 10:16:47.199513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a8684cf235'
down_revision = '537ae9985509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('rebal_dt', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio', 'rebal_dt')
    # ### end Alembic commands ###
