"""empty message

Revision ID: 8613b4042fff
Revises: 26e90966f153
Create Date: 2023-07-21 16:22:50.155664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8613b4042fff'
down_revision = '26e90966f153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simple_transaction', sa.Column('status', sa.String(length=10), nullable=True))
    op.drop_column('simple_transaction', 'is_filled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simple_transaction', sa.Column('is_filled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('simple_transaction', 'status')
    # ### end Alembic commands ###
