"""empty message

Revision ID: b6e008bdfd39
Revises: 5e511bee92e3
Create Date: 2023-07-20 15:28:55.536938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e008bdfd39'
down_revision = '5e511bee92e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simple_transaction', sa.Column('is_filled', sa.Boolean(), nullable=True))
    op.drop_column('simple_transaction', 'is_fiiled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simple_transaction', sa.Column('is_fiiled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('simple_transaction', 'is_filled')
    # ### end Alembic commands ###
