from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "back"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transaction",
        "status",
        existing_type=sa.Enum("open", "canceled", "closed", name="status"),
        type_=sa.VARCHAR(length=10),
        existing_nullable=True,
    )
    op.alter_column(
        "transaction",
        "side",
        existing_type=sa.Enum("buy", "sell", name="side"),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    op.alter_column(
        "transaction",
        "order_type",
        existing_type=sa.Enum("market", "limit", name="order_type"),
        type_=sa.VARCHAR(length=10),
        existing_nullable=True,
    )
    op.add_column(
        "ticker",
        sa.Column("asset_type_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "ticker_asset_type_id_fkey", "ticker", "asset_type", ["asset_type_id"], ["id"]
    )
    op.drop_column("ticker", "asset_type")
    op.create_table(
        "asset_type",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "asset_nm", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "asset_knm", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="asset_type_pkey"),
        sa.UniqueConstraint("asset_knm", name="asset_type_asset_knm_key"),
        sa.UniqueConstraint("asset_nm", name="asset_type_asset_nm_key"),
    )
    op.create_index("ix_asset_type_id", "asset_type", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    pass
