"""empty message

Revision ID: dba38207abb4
Revises: 55a3f107b874
Create Date: 2023-08-02 09:31:51.010685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba38207abb4'
down_revision = '55a3f107b874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_ticker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('ticker_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.ForeignKeyConstraint(['ticker_id'], ['ticker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_ticker_id'), 'portfolio_ticker', ['id'], unique=False)
    op.drop_table('portfolio_memo')
    op.add_column('portfolio', sa.Column('memo', sa.Text(), nullable=True))
    op.drop_constraint('portfolio_ticker_id_fkey', 'portfolio', type_='foreignkey')
    op.drop_column('portfolio', 'weight')
    op.drop_column('portfolio', 'ticker_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('ticker_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('portfolio_ticker_id_fkey', 'portfolio', 'ticker', ['ticker_id'], ['id'])
    op.drop_column('portfolio', 'memo')
    op.create_table('portfolio_memo',
    sa.Column('portfolio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], name='portfolio_memo_portfolio_id_fkey'),
    sa.PrimaryKeyConstraint('portfolio_id', name='portfolio_memo_pkey')
    )
    op.drop_index(op.f('ix_portfolio_ticker_id'), table_name='portfolio_ticker')
    op.drop_table('portfolio_ticker')
    # ### end Alembic commands ###
